### ISSUE TITLE
Would love an ES version!

### ISSUE THREAD

**Issue by outdooricon** [Hokkaidosunny/react-router-enter#1]
Thanks for this lib, it's great! Would you consider adding an es version as well, that wasn't compiled using commonjs modules turned on?

**Comment by Hokkaidosunny** [comment]
```javascript
import onEnter from 'react-router-enter/src/onEnter.js';
```
@outdooricon if this would resolve your problem?

**Comment by outdooricon** [comment]
Unfortunately no, since it's a node_modle import, it still needs to go through other babel transpilation, just not the commonjs modules one.

**Comment by Hokkaidosunny** [comment]
```
presets: [
      ["es2015", {
        "modules": false
      }],
      'react',
      'stage-0'
    ],
]
```
@outdooricon set modules = false, babel will not transform modules
